### ISSUE TITLE
Error: Sprockets::Rails::Helper::AssetFilteredError

### ISSUE THREAD

**Issue by samu** [modeset/teaspoon#197]
After generating the initial teaspoon files, i get this error when i try to run `rake teaspoon`: 

```
Error: Sprockets::Rails::Helper::AssetFilteredError: Asset filtered out and will not be served: 
add `Rails.application.config.assets.precompile += %w( teaspoon.css )` to `config/initializers/assets.rb` and restart your server
```

I have to add several lines such as

`Rails.application.config.assets.precompile += %w( teaspoon.css )`

 to an initializer file in order to successfully run the specs.

**Comment by grantgeorge** [comment]
I was able to fix this error by adding

```
Rails.application.config.assets.precompile += %w(
  teaspoon.css
  teaspoon-teaspoon.js
  teaspoon-jasmine.js
  jasmine/1.3.1.js
)
```

to config/initializers/assets.rb

**Comment by jejacks0n** [comment]
Confirmed this is fixed in master (with some minor tweaks), and will be included in the next release.

**Comment by ccallebs** [comment]
After installing a fresh version I'm still getting this issue.

Gem versions
```
teaspoon (1.1.1)
teaspoon-jasmine (2.3.4)
```

Everything else is in place from the install, except for removing

``` coffeescript
#= require application
```

from spec_helper.coffee.

**Comment by wanchic** [comment]
Using teaspoon with without coffee-script, I too am getting these errors.

Gem versions
```ruby
teaspoon 1.1.1
teaspoon-jasmine 2.3.4
sprockets 3.5.2
```

I discovered that the issue stems from on of this upgrade:
```ruby
-    sprockets-rails (2.3.3)
-      actionpack (>= 3.0)
-      activesupport (>= 3.0)
-      sprockets (>= 2.8, < 4.0)
+    sprockets-rails (3.0.0)
+      actionpack (>= 4.0)
+      activesupport (>= 4.0)
+      sprockets (>= 3.0.0)
```

As long as sprockets-rails is kept at 2.3.3, you should be fine. v3.0.0 seems to conflict at the moment. 

Hope this helps (^_^)

**Comment by jejacks0n** [comment]
https://github.com/modeset/teaspoon/issues/443
