### ISSUE TITLE
Coverage does not show up with expand_assets set to false

### ISSUE THREAD

**Issue by mikepack** [modeset/teaspoon#357]
With `config.use_coverage = :default`.

Maybe since the spec helper is excluded from coverage, and everything is compiled down, coverage is not being reported?

**Comment by mikepack** [comment]
Coverage is not recognized because `_helper` is included in `coverage.ignore` by default, and application (and everything else) gets required from there.

Instrumentation is still not added because the logic [here](https://github.com/modeset/teaspoon/blob/master/lib/teaspoon/suite.rb#L54-L58) is not correct. If `expand_assets` is turned on, `instrument=1` is never added to any file. Should probably be something more like:

```ruby
unless asset && asset.respond_to?(:logical_path)
  return source.blank? ? nil : source
end

if config.expand_assets
  asset.to_a.map { |a| asset_url(a) }
else
  asset_url(asset)
end
```

**Comment by mikepack** [comment]
Fixed in 1fdfaae3c8a85d3b65c1895147d5a38ecefd6cdd

**Comment by andresbravog** [comment]
This is still happening. `config.expand_assets = false` makes the spec_helper to not be instrumented
